/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
    images: {
        domains: [
            'www.ropebox.ru',
            'www.henrilloyd.com',
            'tradeonly.harken.com',
            'bluesea.com',
            'www.marinebusiness.net',
            'www.glomex.it',
            'www.fordewind-regatta.ru',
            'imagecache2.allposters.com',
            'www.saint-james-tricots.com',
            'www.fordewind.spb.ru',
            'www.saint-james.co.uk',
            'www.bainbridgemarine.co.uk',
            'authenticmodels.com',
            'www.ronstan.com',
            'www.nauticalia.com',
            'www.tacktick.com',
            'media.suunto.com',
            'www.can-web.com',
            'www.cansb.com',
            'www.spinlock.co.uk',
            'www.optiparts.com',
            'www.clamcleat.com',
            'deel.ru',
            'nethouse.ru',
            'marinemotor.ru',
            'ropebox.ru',
            'www.craftsmanmarine.com',
            'windsportspune.com',
            'gillmarine.com',
            'kauppa.maritim.fi',
            'www.best-krepeg.ru',
            'www.cansrl.com',
            'www.arimar.com',
            'typhoon-pro.ru',
            'www.bainbridgeint.com',
            'www.blueperformance.com',
            'www.mobyboatshoes.com',
            'fordewind-regatta.ru',
            'www.plastimo.com',
            'www.nasamarine.com',
            'www.wilks.co.uk',
            'www.allenbrothers.co.uk',
            'www.gillmarine.com',
            'loosnaples.com',
            'www.harken.com',
            'www.trem.net',
            'vsails.ru',
            'www.seldenmast.com',
            'paints.nautix.com',
            'www.vtsport.ru',
            'vtsport.ru',
        ],
    },
};

export default nextConfig;
